#!/system/bin/sh
BASEDIR=$(dirname "$0")

if [ ! -f "$BASEDIR"/sui.dex ]; then
  echo "[ sui.dex not found, please copy sui.dex from /data/adb/sui ]"
  exit 1
fi

if [ ! -r "$BASEDIR"/sui.dex ]; then
  echo "[ sui.dex is not readable, please check the permission ]"
  exit 1
fi

/system/bin/app_process -Djava.class.path="$BASEDIR"/sui.dex /system/bin --nice-name=sui_cmd rikka.sui.cmd.SuiCmd "$@"
