#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/sui.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check post-install.sh"
  exit 1
fi

if [ ! -r "$DEX" ]; then
  echo "Cannot read $DEX, please check post-install.sh"
  exit 1
fi

export SUI_APPLICATION_ID=%%%SUI_APPLICATION_ID%%%
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=sui_wrapper rikka.sui.cmd.SuiCmd "$@"
